services:
  database: #DB for testing
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: exploitfarm
      POSTGRES_PASSWORD: exploitfarm
      POSTGRES_DB: exploitfarm
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

