services:
  database: #DB for testing
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: exploitfarm
      POSTGRES_PASSWORD: exploitfarm
      POSTGRES_DB: exploitfarm
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  redis: #Redis for testing
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379

