[project]

name = "backend"
version = "0.0.0"
description = "ExploitFarm backend"
requires-python = ">=3.12, <3.13"

dependencies = [
    "aiocache==0.12.3",
    "fastapi[all]==0.115.3",
    "httpx==0.27.2",
    "passlib[bcrypt]==1.7.4",
    "pwntools>=4.13.1",
    "requests>=2.32.3",
    "uvicorn[standard]==0.32.0",
    "databases==0.7.0",
    "asyncpg==0.30.0",
    "psycopg2-binary==2.9.10",
    "uvloop==0.21.0",
    "fastapi-pagination==0.12.31",
    "pyjwt==2.9.0",
    "fasteners==0.19",
    "dirhash==0.5.0",
    "python-multipart==0.0.12",
    "ormar==0.20.1",
    "exploitfarm",
    "orjson",
]

[tool.setuptools.packages]
# Explicitly list the directories you want to package
find = {include = ["models", "routes"]}
